name: tradicional
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf: ^1.4.0
  dart_jsonwebtoken: ^2.8.2
  sqlite3: ^2.2.0
  path: ^1.9.0
  bcrypt: ^1.1.3
  shelf_router: ^1.1.3


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
